
package packCurs;

import java.awt.BasicStroke;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

/**
 *
 * @author Antal Tiberiu
 */
public class NewJPanel extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public NewJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
    }//GEN-END:initComponents

    public void paintComponent(Graphics g) {      
        super.paintComponent(g);
          Graphics2D g2 = (Graphics2D) g;
          Shape r = new Rectangle2D.Double(10.,5.,550.,30.);
          g2.fill(r);
          Ellipse2D e = new Ellipse2D.Double(100.,100.,200.,300.);
          g2.draw(e);
          g2.setStroke(new BasicStroke(5.f));
          Line2D l = new Line2D.Double(100., 100., 200., 300.);
          g2.draw(l);
          float dashpoint[] = { 2, 5, 20, 5 }; //{on, off, on, of, ...}
          g2.setStroke(new BasicStroke(0.0f, BasicStroke.CAP_BUTT, BasicStroke.JOIN_MITER, 10.0f, dashpoint, 0.0f));
          Line2D l1 = new Line2D.Double(100., 300., 200., 100.);
          g2.draw(l1);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
